version: '3.8'

services:

  backend-test:
    build:
      context: ./backend
      dockerfile: Dockerfile.test
    ports:
      - "8888:8888"
    volumes:
      - ./backend:/usr/src/app
    env_file:
      - ./backend/.env.test
