version: '3.8'

services:

  backend:
    build: ./backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis
    env_file:
      - ./backend/.env.dev

  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  db:
    image: mysql:8.0
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=anisong
    volumes:
      - ./backend/data/mysql/:/var/lib/mysql

  redis:
    image: redis/redis-stack-server:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - ./backend/data/redis/:/data
