version: '3.1'

services:

  db:
    image: mysql:8.0
    container_name: mysql_container
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - "./backend/create.sql:/docker-entrypoint-initdb.d/create.sql"
    environment:
      MYSQL_ROOT_PASSWORD: root
