version: '3.8'

services:

  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

  backend:
    context: ./backend
    dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis
    env_file:
      - ./backend/.env.dev

  frontend:
    context: ./backend
    dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  db:
    image: mysql:8.0
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=anisong
    volumes:
      - ./backend/data/mysql/:/var/lib/mysql

  redis:
    image: redis/redis-stack-server:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - ./backend/data/redis/:/data
