version: '3.1'

services:

  db:
    image: mysql:8.0
    container_name: mysql_container
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - "./backend/create.sql:/docker-entrypoint-initdb.d/create.sql"
    environment:
      - MYSQL_ROOT_PASSWORD=root

  backend:
    build: ./backend
    ports:
      - "80:80"
    volumes:
      - "./backend:/app"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=newuser
      - MYSQL_PASSWORD=password2
      - MYSQL_DATABASE=AniSong
