version: '3.8'

services:

  backend:
    build: ./backend
    ports:
      - "80:80"
    volumes:
      - "./backend:/app"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql+pymysql://root:root@db/anisong

  db:
    image: mysql:8.0
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=anisong
