"""Add association table Favorite

Revision ID: 234bdf8eab51
Revises: cd58c3b3913f
Create Date: 2023-07-18 09:25:17.444507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '234bdf8eab51'
down_revision = 'cd58c3b3913f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('music_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['music_id'], ['music.id'], name='favorite_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorite_ibfk_1'),
    sa.PrimaryKeyConstraint('music_id', 'user_id')
    )
    op.create_index('ix_favorite_user_id', 'favorite', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_favorite_user_id', table_name='favorite')
    op.drop_table('favorite')
    # ### end Alembic commands ###
