"""Add request music and notification table

Revision ID: 3239bf911430
Revises: c0f931a9b805
Create Date: 2024-09-10 15:08:27.698149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3239bf911430'
down_revision = 'c0f931a9b805'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_music',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.Column('video_id', sa.String(length=50), nullable=False),
    sa.Column('music_name', sa.String(length=255), nullable=False),
    sa.Column('anime_name', sa.String(length=255), nullable=False),
    sa.Column('artists', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['type.id'], name=op.f('fk_request_music_type_id_type'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_request_music_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_request_music'))
    )
    op.create_index(op.f('ix_request_music_type_id'), 'request_music', ['type_id'], unique=False)
    op.create_index(op.f('ix_request_music_user_id'), 'request_music', ['user_id'], unique=False)
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('music_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['music_id'], ['music.id'], name=op.f('fk_notification_music_id_music'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_notification_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification'))
    )
    op.create_index(op.f('ix_notification_music_id'), 'notification', ['music_id'], unique=False)
    op.create_index(op.f('ix_notification_user_id'), 'notification', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_notification_music_id_music'), table_name='notification', type_='foreignkey')
    op.drop_constraint(op.f('fk_notification_user_id_user'), table_name='notification', type_='foreignkey')
    op.drop_index(op.f('ix_notification_user_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_music_id'), table_name='notification')
    op.drop_table('notification')
    op.drop_constraint(op.f('fk_request_music_type_id_type'), table_name='request_music', type_='foreignkey')
    op.drop_constraint(op.f('fk_request_music_user_id_user'), table_name='request_music', type_='foreignkey')
    op.drop_index(op.f('ix_request_music_user_id'), table_name='request_music')
    op.drop_index(op.f('ix_request_music_type_id'), table_name='request_music')
    op.drop_table('request_music')
    # ### end Alembic commands ###
