"""Update name table profile_picture

Revision ID: 3cdae4912e18
Revises: f8c8a284fe59
Create Date: 2023-05-10 12:41:04.419416

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3cdae4912e18'
down_revision = 'f8c8a284fe59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_picture', sa.String(length=250), nullable=True))
    op.drop_column('user', 'profil_picture')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profil_picture', mysql.VARCHAR(length=250), nullable=True))
    op.drop_column('user', 'profile_picture')
    # ### end Alembic commands ###
