"""change tables

Revision ID: 8a5eb65ad2c0
Revises: b7aa7bc08494
Create Date: 2023-04-25 16:55:02.490313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a5eb65ad2c0'
down_revision = 'b7aa7bc08494'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
