"""Add column creation_year in Author table

Revision ID: 9c1f2973f1b8
Revises: b1448813806f
Create Date: 2023-05-23 13:53:13.931189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c1f2973f1b8'
down_revision = 'b1448813806f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('creation_year', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('author', 'creation_year')
    # ### end Alembic commands ###
