"""Change column name from music to unique

Revision ID: b1448813806f
Revises: a544f5a7c282
Create Date: 2023-05-11 13:13:35.338332

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b1448813806f'
down_revision = 'a544f5a7c282'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('music', 'release_date',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.create_unique_constraint(None, 'music', ['name'])
    op.alter_column('review', 'creation_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('review', 'creation_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_constraint(None, 'music', type_='unique')
    op.alter_column('music', 'release_date',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    # ### end Alembic commands ###
