"""Initial tables

Revision ID: c0f931a9b805
Revises: 
Create Date: 2024-09-10 14:33:51.840460

"""
import os
from alembic import op
import sqlalchemy as sa

from app.utils import get_password_hash

# revision identifiers, used by Alembic.
revision = 'c0f931a9b805'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poster_img', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_anime'))
    )
    op.create_table('artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('poster_img', sa.String(length=250), nullable=False),
    sa.Column('creation_year', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artist')),
    sa.UniqueConstraint('name', name=op.f('uq_artist_name'))
    )
    op.create_table('supported_language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supported_language')),
    sa.UniqueConstraint('code', name=op.f('uq_supported_language_code'))
    )
    op.create_table('type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_type'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('is_manager', sa.Boolean(), nullable=False),
    sa.Column('profile_picture', sa.String(length=250), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=False, 
              server_default=sa.text("CURRENT_TIMESTAMP")),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email')),
    sa.UniqueConstraint('username', name=op.f('uq_user_username'))
    )

    op.execute(
        f"INSERT INTO user (username, email, password, is_manager, profile_picture) VALUES ('{os.getenv('USERNAME_ADMIN')}', 'admin@gmail.com', '{get_password_hash(os.getenv('PASSWORD_ADMIN'))}', 1, null);")

    op.create_table('anime_translation',
    sa.Column('id_anime', sa.Integer(), nullable=False),
    sa.Column('id_language', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id_anime'], ['anime.id'], name=op.f('fk_anime_translation_id_anime_anime'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_language'], ['supported_language.id'], name=op.f('fk_anime_translation_id_language_supported_language'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_anime', 'id_language', name=op.f('pk_anime_translation'))
    )
    op.create_index(op.f('ix_anime_translation_id_anime'), 'anime_translation', ['id_anime'], unique=False)
    op.create_index(op.f('ix_anime_translation_id_language'), 'anime_translation', ['id_language'], unique=False)
    op.create_table('music',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('release_date', sa.DateTime(), nullable=False),
    sa.Column('avg_note', sa.Float(), nullable=True),
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('poster_img', sa.String(length=250), nullable=True),
    sa.Column('id_video', sa.String(length=25), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], name=op.f('fk_music_anime_id_anime')),
    sa.ForeignKeyConstraint(['type_id'], ['type.id'], name=op.f('fk_music_type_id_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_music')),
    sa.UniqueConstraint('name', name=op.f('uq_music_name'))
    )
    op.create_index(op.f('ix_music_anime_id'), 'music', ['anime_id'], unique=False)
    op.create_index(op.f('ix_music_type_id'), 'music', ['type_id'], unique=False)
    op.create_table('type_translation',
    sa.Column('id_type', sa.Integer(), nullable=False),
    sa.Column('id_language', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['id_language'], ['supported_language.id'], name=op.f('fk_type_translation_id_language_supported_language'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_type'], ['type.id'], name=op.f('fk_type_translation_id_type_type'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_type', 'id_language', name=op.f('pk_type_translation'))
    )
    op.create_index(op.f('ix_type_translation_id_language'), 'type_translation', ['id_language'], unique=False)
    op.create_index(op.f('ix_type_translation_id_type'), 'type_translation', ['id_type'], unique=False)
    op.create_table('chante',
    sa.Column('music_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], name=op.f('fk_chante_artist_id_artist'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['music_id'], ['music.id'], name=op.f('fk_chante_music_id_music'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('music_id', 'artist_id', name=op.f('pk_chante'))
    )
    op.create_index(op.f('ix_chante_artist_id'), 'chante', ['artist_id'], unique=False)
    op.create_index(op.f('ix_chante_music_id'), 'chante', ['music_id'], unique=False)
    op.create_table('favorite',
    sa.Column('music_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['music_id'], ['music.id'], name=op.f('fk_favorite_music_id_music'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_favorite_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('music_id', 'user_id', name=op.f('pk_favorite'))
    )
    op.create_index(op.f('ix_favorite_music_id'), 'favorite', ['music_id'], unique=False)
    op.create_index(op.f('ix_favorite_user_id'), 'favorite', ['user_id'], unique=False)
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_visual', sa.Float(), nullable=False),
    sa.Column('note_music', sa.Float(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('music_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['music_id'], ['music.id'], name=op.f('fk_review_music_id_music'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_review_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review'))
    )
    op.create_index(op.f('ix_review_music_id'), 'review', ['music_id'], unique=False)
    op.create_index(op.f('ix_review_user_id'), 'review', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_review_music_id_music'), table_name='review', type_='foreignkey')
    op.drop_constraint(op.f('fk_review_user_id_user'), table_name='review', type_='foreignkey')
    op.drop_index(op.f('ix_review_user_id'), table_name='review')
    op.drop_index(op.f('ix_review_music_id'), table_name='review')
    op.drop_table('review')
    op.drop_constraint(op.f('fk_favorite_music_id_music'), table_name='favorite', type_='foreignkey')
    op.drop_constraint(op.f('fk_favorite_user_id_user'), table_name='favorite', type_='foreignkey')
    op.drop_index(op.f('ix_favorite_user_id'), table_name='favorite')
    op.drop_index(op.f('ix_favorite_music_id'), table_name='favorite')
    op.drop_table('favorite')
    op.drop_constraint(op.f('fk_chante_artist_id_artist'), table_name='chante', type_='foreignkey')
    op.drop_constraint(op.f('fk_chante_music_id_music'), table_name='chante', type_='foreignkey')
    op.drop_index(op.f('ix_chante_music_id'), table_name='chante')
    op.drop_index(op.f('ix_chante_artist_id'), table_name='chante')
    op.drop_table('chante')
    op.drop_constraint(op.f('fk_type_translation_id_language_supported_language'), table_name='type_translation', type_='foreignkey')
    op.drop_constraint(op.f('fk_type_translation_id_type_type'), table_name='type_translation', type_='foreignkey')
    op.drop_index(op.f('ix_type_translation_id_type'), table_name='type_translation')
    op.drop_index(op.f('ix_type_translation_id_language'), table_name='type_translation')
    op.drop_table('type_translation')
    op.drop_constraint(op.f('fk_music_anime_id_anime'), table_name='music', type_='foreignkey')
    op.drop_constraint(op.f('fk_music_type_id_type'), table_name='music', type_='foreignkey')
    op.drop_index(op.f('ix_music_type_id'), table_name='music')
    op.drop_index(op.f('ix_music_anime_id'), table_name='music')
    op.drop_table('music')
    op.drop_constraint(op.f('fk_anime_translation_id_anime_anime'), table_name='anime_translation', type_='foreignkey')
    op.drop_constraint(op.f('fk_anime_translation_id_language_supported_language'), table_name='anime_translation', type_='foreignkey')
    op.drop_index(op.f('ix_anime_translation_id_language'), table_name='anime_translation')
    op.drop_index(op.f('ix_anime_translation_id_anime'), table_name='anime_translation')
    op.drop_table('anime_translation')
    op.drop_table('user')
    op.drop_table('type')
    op.drop_table('supported_language')
    op.drop_table('artist')
    op.drop_table('anime')
    # ### end Alembic commands ###
